services:
  resume_parser:
    container_name: resume_parser
    build: .
    expose:
      - "6080"
    env_file:
      - .env
    networks:
      - app-network-dev
      # - app-network-prod

networks:
  app-network-dev:
    external:
      name: app-network-dev
  # app-network-prod:
  #   external:
  #     name: app-network-prod